spring.application.name=itau-desafio-cartoes

#SERVER
server.port=8080
spring.web.error.include-stacktrace=never

#DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/itau-cartoes
spring.datasource.username=dev
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#API RESPONSE STYLE
spring.jackson.property-naming-strategy=SNAKE_CASE

